language: go

go:
- 1.10.2

go_import_path: github.com/kubernetes-incubator/apiserver-builder-alpha

cache:
  directories:
  - $HOME/.glide
  - /usr/local/kubebuilder/bin

git:
  depth: 3

env:
  - TEST=example
  - TEST=test

install:
  - scripts/install_etcd.sh

script:
        ./test/travis.sh
