language: go

go:
- 1.12.2

go_import_path: sigs.k8s.io/apiserver-builder-alpha

cache:
  directories:
  - $HOME/.glide
  - /usr/local/kubebuilder/bin

git:
  depth: 3

install:
  - scripts/install_etcd.sh

jobs:
  include:
    - stage: Test Example
      env: TEST=example
      script: sudo env "PATH=$PATH" ./test/travis.sh

    - stage: Test New Project
      env: TEST=test
      script: sudo env "PATH=$PATH" ./test/travis.sh
