
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.innsmouth.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1
  group: innsmouth.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUxGVnk0V3A0YVJ1TUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF5TXpFeE1qQXpNbG9YRFRJeE1UQXlNekV4TWpBek1sb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzFEd3lwTy9tL3BaRmYKa2tzK2E4WExTQ05XQytpSm5PdU1jQTdVeS9SYzFZMTBVYTk2UVlqNUM1SFdQK3pzc05zQTdDS0JTa3ZORy9mRApSVzlFSFlRRjFnQnhWZ1Q2SGsvcERVWndDYkloaWRzQUdKeFZuWU1HR01ucGh2M3R1eTE4OXJYWTNQZ0FCMXA3Clord3p2NU44TE5UMVFRdlNOZUlRemtXdlpFU1AzRHpXWnorTmc2eElJT0ViL2tSYS84SVQ2ZTEzWUUvVXJqS0gKdDljRDNBOWo5OW81TEtJOTBEN2Z0dUR6VkRwNURrZFJHc0dMaDY3UnpmcGZxZlgrcW5EaUd0SWp3ei95ZVpETQpVYzE3SmZuTjRheEJBK2FCRzdnWFdMVzY2VFNPb2VwY1ZNbnkvS1RBVVFZU0xBSjdVbGNHRi95cFR2SE03S0pxCmYweXIxREZqQWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBSFkvM09lWVlnMnJSdDVzZ2pEMGdDT1dXeTI1K1FhcURyYWpHNUNteTFTNG1DV242TkZnN1dScQpWZjgrY0hrYWxic1R6WXY4cjRMSTZJdFFjditVN3AvSnZ5eitZcUh4VW8xSm9mNThuV0hGSFZxaGM0T2V3eXNOCnRhU3VPcmVjUFlORTZPb2ZtWkMyek9GVC9uNzVVMVBzYU1oVEpQemdtdTkwdkYwNWhSQzFSTzVkQ3IxVVJKbHUKZEt1WEszdmU1R2VSNDkzK0NLWXlUYlhnYWUyTXpJQW9leDFJWHJ5VXVCc2N0QnpTbDlFayttUlVKYlNlN2c0QwpmNEpRdk9teWx4MDM0NUEyNUJaZ3QvUWNlZXl2VEZ0TU0zVlRWSk5ieW5tVk1rU0d4bzUrTWFHRURTN2RtbFAxCkNhVUFuUzR1TjJkRG1BNjFYQ1AzZlN2NU04MWYyUmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.kingsport.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1
  group: kingsport.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUxGVnk0V3A0YVJ1TUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF5TXpFeE1qQXpNbG9YRFRJeE1UQXlNekV4TWpBek1sb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzFEd3lwTy9tL3BaRmYKa2tzK2E4WExTQ05XQytpSm5PdU1jQTdVeS9SYzFZMTBVYTk2UVlqNUM1SFdQK3pzc05zQTdDS0JTa3ZORy9mRApSVzlFSFlRRjFnQnhWZ1Q2SGsvcERVWndDYkloaWRzQUdKeFZuWU1HR01ucGh2M3R1eTE4OXJYWTNQZ0FCMXA3Clord3p2NU44TE5UMVFRdlNOZUlRemtXdlpFU1AzRHpXWnorTmc2eElJT0ViL2tSYS84SVQ2ZTEzWUUvVXJqS0gKdDljRDNBOWo5OW81TEtJOTBEN2Z0dUR6VkRwNURrZFJHc0dMaDY3UnpmcGZxZlgrcW5EaUd0SWp3ei95ZVpETQpVYzE3SmZuTjRheEJBK2FCRzdnWFdMVzY2VFNPb2VwY1ZNbnkvS1RBVVFZU0xBSjdVbGNHRi95cFR2SE03S0pxCmYweXIxREZqQWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBSFkvM09lWVlnMnJSdDVzZ2pEMGdDT1dXeTI1K1FhcURyYWpHNUNteTFTNG1DV242TkZnN1dScQpWZjgrY0hrYWxic1R6WXY4cjRMSTZJdFFjditVN3AvSnZ5eitZcUh4VW8xSm9mNThuV0hGSFZxaGM0T2V3eXNOCnRhU3VPcmVjUFlORTZPb2ZtWkMyek9GVC9uNzVVMVBzYU1oVEpQemdtdTkwdkYwNWhSQzFSTzVkQ3IxVVJKbHUKZEt1WEszdmU1R2VSNDkzK0NLWXlUYlhnYWUyTXpJQW9leDFJWHJ5VXVCc2N0QnpTbDlFayttUlVKYlNlN2c0QwpmNEpRdk9teWx4MDM0NUEyNUJaZ3QvUWNlZXl2VEZ0TU0zVlRWSk5ieW5tVk1rU0d4bzUrTWFHRURTN2RtbFAxCkNhVUFuUzR1TjJkRG1BNjFYQ1AzZlN2NU04MWYyUmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.miskatonic.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1beta1
  group: miskatonic.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUxGVnk0V3A0YVJ1TUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF5TXpFeE1qQXpNbG9YRFRJeE1UQXlNekV4TWpBek1sb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzFEd3lwTy9tL3BaRmYKa2tzK2E4WExTQ05XQytpSm5PdU1jQTdVeS9SYzFZMTBVYTk2UVlqNUM1SFdQK3pzc05zQTdDS0JTa3ZORy9mRApSVzlFSFlRRjFnQnhWZ1Q2SGsvcERVWndDYkloaWRzQUdKeFZuWU1HR01ucGh2M3R1eTE4OXJYWTNQZ0FCMXA3Clord3p2NU44TE5UMVFRdlNOZUlRemtXdlpFU1AzRHpXWnorTmc2eElJT0ViL2tSYS84SVQ2ZTEzWUUvVXJqS0gKdDljRDNBOWo5OW81TEtJOTBEN2Z0dUR6VkRwNURrZFJHc0dMaDY3UnpmcGZxZlgrcW5EaUd0SWp3ei95ZVpETQpVYzE3SmZuTjRheEJBK2FCRzdnWFdMVzY2VFNPb2VwY1ZNbnkvS1RBVVFZU0xBSjdVbGNHRi95cFR2SE03S0pxCmYweXIxREZqQWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBSFkvM09lWVlnMnJSdDVzZ2pEMGdDT1dXeTI1K1FhcURyYWpHNUNteTFTNG1DV242TkZnN1dScQpWZjgrY0hrYWxic1R6WXY4cjRMSTZJdFFjditVN3AvSnZ5eitZcUh4VW8xSm9mNThuV0hGSFZxaGM0T2V3eXNOCnRhU3VPcmVjUFlORTZPb2ZtWkMyek9GVC9uNzVVMVBzYU1oVEpQemdtdTkwdkYwNWhSQzFSTzVkQ3IxVVJKbHUKZEt1WEszdmU1R2VSNDkzK0NLWXlUYlhnYWUyTXpJQW9leDFJWHJ5VXVCc2N0QnpTbDlFayttUlVKYlNlN2c0QwpmNEpRdk9teWx4MDM0NUEyNUJaZ3QvUWNlZXl2VEZ0TU0zVlRWSk5ieW5tVk1rU0d4bzUrTWFHRURTN2RtbFAxCkNhVUFuUzR1TjJkRG1BNjFYQ1AzZlN2NU04MWYyUmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.olympus.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1beta1
  group: olympus.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUxGVnk0V3A0YVJ1TUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF5TXpFeE1qQXpNbG9YRFRJeE1UQXlNekV4TWpBek1sb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzFEd3lwTy9tL3BaRmYKa2tzK2E4WExTQ05XQytpSm5PdU1jQTdVeS9SYzFZMTBVYTk2UVlqNUM1SFdQK3pzc05zQTdDS0JTa3ZORy9mRApSVzlFSFlRRjFnQnhWZ1Q2SGsvcERVWndDYkloaWRzQUdKeFZuWU1HR01ucGh2M3R1eTE4OXJYWTNQZ0FCMXA3Clord3p2NU44TE5UMVFRdlNOZUlRemtXdlpFU1AzRHpXWnorTmc2eElJT0ViL2tSYS84SVQ2ZTEzWUUvVXJqS0gKdDljRDNBOWo5OW81TEtJOTBEN2Z0dUR6VkRwNURrZFJHc0dMaDY3UnpmcGZxZlgrcW5EaUd0SWp3ei95ZVpETQpVYzE3SmZuTjRheEJBK2FCRzdnWFdMVzY2VFNPb2VwY1ZNbnkvS1RBVVFZU0xBSjdVbGNHRi95cFR2SE03S0pxCmYweXIxREZqQWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBSFkvM09lWVlnMnJSdDVzZ2pEMGdDT1dXeTI1K1FhcURyYWpHNUNteTFTNG1DV242TkZnN1dScQpWZjgrY0hrYWxic1R6WXY4cjRMSTZJdFFjditVN3AvSnZ5eitZcUh4VW8xSm9mNThuV0hGSFZxaGM0T2V3eXNOCnRhU3VPcmVjUFlORTZPb2ZtWkMyek9GVC9uNzVVMVBzYU1oVEpQemdtdTkwdkYwNWhSQzFSTzVkQ3IxVVJKbHUKZEt1WEszdmU1R2VSNDkzK0NLWXlUYlhnYWUyTXpJQW9leDFJWHJ5VXVCc2N0QnpTbDlFayttUlVKYlNlN2c0QwpmNEpRdk9teWx4MDM0NUEyNUJaZ3QvUWNlZXl2VEZ0TU0zVlRWSk5ieW5tVk1rU0d4bzUrTWFHRURTN2RtbFAxCkNhVUFuUzR1TjJkRG1BNjFYQ1AzZlN2NU04MWYyUmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
