
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.innsmouth.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1
  group: innsmouth.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUlobG1HMHFyNFhxTUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF4TkRBM01qSTFNVm9YRFRJeE1UQXhOREEzTWpJMU1Wb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFhxZXNlUU5QZE90MzQKV256RVFWRDNZTFF5UmplYWhPeXJ3SllEVzRkc3VjUkozcFY3S0Y1R29TNC9UNkhQeCtOaVNma1JQTFJkWVVueQoyTWk0Ti9NNHBONXZzSU5obVVueWxmN0dxRzlFMnhUNGRaVkVjWWpJa2dIQjJ2Q1RxOU1QVldrTVhXMlMvbWd1ClBKNGNUS1Y5cXNHVUViazJhZVBJOEE4NTFhRlYvaWNMRkR5OFNLa3o3OWRscUlnUzdVSG53bE4yMXVrdXdmdHEKa1dIanB6dnlLNW55c2IvRDZ0NWpSY1FxVU52bmhMSlFUTklpUGxVM24zTm9IZVoxLzZDdmQvT3dLUVdpTjhWcwowSWsxYmNnNkRhei9xSUdCN3UrYVZXUkhtbEgwNk5CWFIyOWtyakxiUDVBZmFNSzZQZFBMdFJKQjdkM2FiUzY1CkV3SVZ1aFd4QWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBR3UxeXJwWUZXakt1U2taSFdRK2FXZjdjZEFwbUJNQ0tiMHFCb0doUTZVVUl3UEp1dGJLQ2tzTQo0N2hiV2RTTEM0anJOeWt0YVN3N3prV2RpMUI4SWJsQnRJa2VmVGdOR3o3Q3U0bjR1WklUMlNaeXgxL2MwekVBCndHR1AzRlhZUmJTbGV2WDVLVCtKNlNDOFJheG1MeU5SK0ZjbndkRW1LL0poZzVyaTBMeUgyK3ArZEVXbEVLWTgKL1FubnkyVUNPUSsvc2RyTG9IM0JvNUVCUWZlMStTWjFFZFVmaEFxWDVVejROWGFpaEU3SzNTN0RaSFZWZXk1dApKU0Q5blhzb0VJZWNpblVKY1pVeFVvZTA2MmRxdW85TXh4TXUxVFU1NlNabnJycTFBT1lVVmlqN3lNWG84UC96CmJYZUw3NG4wZmxqNCtUbjcxYlE3bnhZNm1aNEhDOG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.kingsport.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1
  group: kingsport.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUlobG1HMHFyNFhxTUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF4TkRBM01qSTFNVm9YRFRJeE1UQXhOREEzTWpJMU1Wb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFhxZXNlUU5QZE90MzQKV256RVFWRDNZTFF5UmplYWhPeXJ3SllEVzRkc3VjUkozcFY3S0Y1R29TNC9UNkhQeCtOaVNma1JQTFJkWVVueQoyTWk0Ti9NNHBONXZzSU5obVVueWxmN0dxRzlFMnhUNGRaVkVjWWpJa2dIQjJ2Q1RxOU1QVldrTVhXMlMvbWd1ClBKNGNUS1Y5cXNHVUViazJhZVBJOEE4NTFhRlYvaWNMRkR5OFNLa3o3OWRscUlnUzdVSG53bE4yMXVrdXdmdHEKa1dIanB6dnlLNW55c2IvRDZ0NWpSY1FxVU52bmhMSlFUTklpUGxVM24zTm9IZVoxLzZDdmQvT3dLUVdpTjhWcwowSWsxYmNnNkRhei9xSUdCN3UrYVZXUkhtbEgwNk5CWFIyOWtyakxiUDVBZmFNSzZQZFBMdFJKQjdkM2FiUzY1CkV3SVZ1aFd4QWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBR3UxeXJwWUZXakt1U2taSFdRK2FXZjdjZEFwbUJNQ0tiMHFCb0doUTZVVUl3UEp1dGJLQ2tzTQo0N2hiV2RTTEM0anJOeWt0YVN3N3prV2RpMUI4SWJsQnRJa2VmVGdOR3o3Q3U0bjR1WklUMlNaeXgxL2MwekVBCndHR1AzRlhZUmJTbGV2WDVLVCtKNlNDOFJheG1MeU5SK0ZjbndkRW1LL0poZzVyaTBMeUgyK3ArZEVXbEVLWTgKL1FubnkyVUNPUSsvc2RyTG9IM0JvNUVCUWZlMStTWjFFZFVmaEFxWDVVejROWGFpaEU3SzNTN0RaSFZWZXk1dApKU0Q5blhzb0VJZWNpblVKY1pVeFVvZTA2MmRxdW85TXh4TXUxVFU1NlNabnJycTFBT1lVVmlqN3lNWG84UC96CmJYZUw3NG4wZmxqNCtUbjcxYlE3bnhZNm1aNEhDOG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.miskatonic.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1beta1
  group: miskatonic.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUlobG1HMHFyNFhxTUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF4TkRBM01qSTFNVm9YRFRJeE1UQXhOREEzTWpJMU1Wb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFhxZXNlUU5QZE90MzQKV256RVFWRDNZTFF5UmplYWhPeXJ3SllEVzRkc3VjUkozcFY3S0Y1R29TNC9UNkhQeCtOaVNma1JQTFJkWVVueQoyTWk0Ti9NNHBONXZzSU5obVVueWxmN0dxRzlFMnhUNGRaVkVjWWpJa2dIQjJ2Q1RxOU1QVldrTVhXMlMvbWd1ClBKNGNUS1Y5cXNHVUViazJhZVBJOEE4NTFhRlYvaWNMRkR5OFNLa3o3OWRscUlnUzdVSG53bE4yMXVrdXdmdHEKa1dIanB6dnlLNW55c2IvRDZ0NWpSY1FxVU52bmhMSlFUTklpUGxVM24zTm9IZVoxLzZDdmQvT3dLUVdpTjhWcwowSWsxYmNnNkRhei9xSUdCN3UrYVZXUkhtbEgwNk5CWFIyOWtyakxiUDVBZmFNSzZQZFBMdFJKQjdkM2FiUzY1CkV3SVZ1aFd4QWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBR3UxeXJwWUZXakt1U2taSFdRK2FXZjdjZEFwbUJNQ0tiMHFCb0doUTZVVUl3UEp1dGJLQ2tzTQo0N2hiV2RTTEM0anJOeWt0YVN3N3prV2RpMUI4SWJsQnRJa2VmVGdOR3o3Q3U0bjR1WklUMlNaeXgxL2MwekVBCndHR1AzRlhZUmJTbGV2WDVLVCtKNlNDOFJheG1MeU5SK0ZjbndkRW1LL0poZzVyaTBMeUgyK3ArZEVXbEVLWTgKL1FubnkyVUNPUSsvc2RyTG9IM0JvNUVCUWZlMStTWjFFZFVmaEFxWDVVejROWGFpaEU3SzNTN0RaSFZWZXk1dApKU0Q5blhzb0VJZWNpblVKY1pVeFVvZTA2MmRxdW85TXh4TXUxVFU1NlNabnJycTFBT1lVVmlqN3lNWG84UC96CmJYZUw3NG4wZmxqNCtUbjcxYlE3bnhZNm1aNEhDOG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.olympus.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1beta1
  group: olympus.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lKQUlobG1HMHFyNFhxTUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhMREFxQmdOVkJBTU1JMkpoYzJsakxXVjRZVzF3YkdVdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXdNVEF4TkRBM01qSTFNVm9YRFRJeE1UQXhOREEzTWpJMU1Wb3diVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFhxZXNlUU5QZE90MzQKV256RVFWRDNZTFF5UmplYWhPeXJ3SllEVzRkc3VjUkozcFY3S0Y1R29TNC9UNkhQeCtOaVNma1JQTFJkWVVueQoyTWk0Ti9NNHBONXZzSU5obVVueWxmN0dxRzlFMnhUNGRaVkVjWWpJa2dIQjJ2Q1RxOU1QVldrTVhXMlMvbWd1ClBKNGNUS1Y5cXNHVUViazJhZVBJOEE4NTFhRlYvaWNMRkR5OFNLa3o3OWRscUlnUzdVSG53bE4yMXVrdXdmdHEKa1dIanB6dnlLNW55c2IvRDZ0NWpSY1FxVU52bmhMSlFUTklpUGxVM24zTm9IZVoxLzZDdmQvT3dLUVdpTjhWcwowSWsxYmNnNkRhei9xSUdCN3UrYVZXUkhtbEgwNk5CWFIyOWtyakxiUDVBZmFNSzZQZFBMdFJKQjdkM2FiUzY1CkV3SVZ1aFd4QWdNQkFBR2pGakFVTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBR3UxeXJwWUZXakt1U2taSFdRK2FXZjdjZEFwbUJNQ0tiMHFCb0doUTZVVUl3UEp1dGJLQ2tzTQo0N2hiV2RTTEM0anJOeWt0YVN3N3prV2RpMUI4SWJsQnRJa2VmVGdOR3o3Q3U0bjR1WklUMlNaeXgxL2MwekVBCndHR1AzRlhZUmJTbGV2WDVLVCtKNlNDOFJheG1MeU5SK0ZjbndkRW1LL0poZzVyaTBMeUgyK3ArZEVXbEVLWTgKL1FubnkyVUNPUSsvc2RyTG9IM0JvNUVCUWZlMStTWjFFZFVmaEFxWDVVejROWGFpaEU3SzNTN0RaSFZWZXk1dApKU0Q5blhzb0VJZWNpblVKY1pVeFVvZTA2MmRxdW85TXh4TXUxVFU1NlNabnJycTFBT1lVVmlqN3lNWG84UC96CmJYZUw3NG4wZmxqNCtUbjcxYlE3bnhZNm1aNEhDOG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-example
  namespace: default
  labels:
    api: basic-example
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: basic-example-apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-example-apiserver
  namespace: default
  labels:
    api: basic-example-apiserver
spec:
  selector:
    matchLabels:
      api: basic-example-apiserver
  replicas: 1
  template:
    metadata:
      labels:
        api: basic-example-apiserver
    spec:
      containers:
      - name: apiserver
        image: example.io/basic
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: basic-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-example-controller
  namespace: default
  labels:
    api: basic-example-controller
spec:
  selector:
    matchLabels:
      api: basic-example-controller
  replicas: 1
  template:
    metadata:
      labels:
        api: basic-example-controller
    spec:
      containers:
        - name: controller
          image: example.io/basic
          imagePullPolicy: IfNotPresent
          command:
            - "./controller-manager"
          args:
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 300Mi
      volumes:
        - name: apiserver-certs
          secret:
            secretName: basic-example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: default
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: "etcd"
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        env:
        - name: ETCD_DATA_DIR
          value: /etcd-data-dir
        command:
        - /usr/local/bin/etcd
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://localhost:2379
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data-dir
          mountPath: /etcd-data-dir
        readinessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
  volumeClaimTemplates:
  - metadata:
     name: etcd-data-dir
     annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
         storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: default
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: etcd
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: basic-example
  namespace: default
  labels:
    api: basic-example
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjRENDQWxpZ0F3SUJBZ0lJWTlMUHNjWXkxS2d3RFFZSktvWklodmNOQVFFTEJRQXdiVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXNNQ29HQTFVRUF3d2pZbUZ6YVdNdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3SGhjTk1qQXhNREUwTURjeU1qVXhXaGNOTXpBeE1ERXlNRGN5TWpVeVdqQWtNU0l3SUFZRFZRUUQKRXhsaVlYTnBZeTFsZUdGdGNHeGxMbVJsWm1GMWJIUXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBdTEwN2k2ZmxQYUNtY21sL0tCT0xGL2thZGxTSkRIR3F1OGNhamp5WExHQm1wQ3BNClNBY09zNC9vQ1hoRlNjc284ZVQwK2Q4cHBQMFRyaVFkVjBZS3BJeFQ2TmQybFk3ZlFuMXcrQkZ6SGFWVUVGenQKTUdVc3B3OCtPUStKY3BCN3JwYmh1UXR3RUMrWnUzcU5NM2x0aGZsTFpOV2UyQUE4RGs1WG5HejFBclErSllJNgptOFExTWhiNnQvQnBxdCtwWmVHeC9YcUhDZmczbU02Qkl5Yy9mQzJ4VW9lVFlseGhIVTJndUErQUJHdFlKa2ExCnV3WTZRenVXckRBVlcwdWZBY2h0U1V6UWlFdXNlblVoTEp1NjJpckNYQ2RkSEdjOWF3NmZERTZ1QlRuVEFJcFYKRXljQit0OUo3UDVJbThIbVRJUitBVXRFZjhNd1NUTkxYYlkwQVFJREFRQUJvMTB3V3pBT0JnTlZIUThCQWY4RQpCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQ29HQTFVZEVRUWpNQ0dDCkdXSmhjMmxqTFdWNFlXMXdiR1V1WkdWbVlYVnNkQzV6ZG1PSEJIOEFBQUV3RFFZSktvWklodmNOQVFFTEJRQUQKZ2dFQkFMZktVRlRtWjZra3VVQm85ZFFBTGc5bThwUStNbElOWGE3RzhpNkVkMGgwMURNL0NLM2ZwYUFBcFNvRwpnMGpoUmZESzloT0tPejZlQUIyWEZOOWNBZGtNT0doZVgzbTRveUtHYmVmV1N0eS9MMlRnSlQ2dEFqZVRyaVhaClJSWExJTlo3RXdDNEtwUW8xZmM0djltbVd6NXBkMTBxQnhtckpuNmdabnpYTGZIV1BQMndyckxJMENNUFE0eXUKWnU2cnZrVmg5TnFNTmorYWNiTDFLZy94d0dKbUJ0M1AvNUxpUEV0TUJLUVNtWitLUUFHQmJ5ODFaSU9ZcHNiQwpCU2NLaEs0OHJDdEQybWhLYjNNdEdrU1ljRndXNis4c3dmV2I2UmR4QTRNbUUzSXlVVjRtOXhGaSsyOTUxQ1pZCkQ1OGlRYmhwbnFjazZJMmF3Q3ZhcUFsNTBNZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdTEwN2k2ZmxQYUNtY21sL0tCT0xGL2thZGxTSkRIR3F1OGNhamp5WExHQm1wQ3BNClNBY09zNC9vQ1hoRlNjc284ZVQwK2Q4cHBQMFRyaVFkVjBZS3BJeFQ2TmQybFk3ZlFuMXcrQkZ6SGFWVUVGenQKTUdVc3B3OCtPUStKY3BCN3JwYmh1UXR3RUMrWnUzcU5NM2x0aGZsTFpOV2UyQUE4RGs1WG5HejFBclErSllJNgptOFExTWhiNnQvQnBxdCtwWmVHeC9YcUhDZmczbU02Qkl5Yy9mQzJ4VW9lVFlseGhIVTJndUErQUJHdFlKa2ExCnV3WTZRenVXckRBVlcwdWZBY2h0U1V6UWlFdXNlblVoTEp1NjJpckNYQ2RkSEdjOWF3NmZERTZ1QlRuVEFJcFYKRXljQit0OUo3UDVJbThIbVRJUitBVXRFZjhNd1NUTkxYYlkwQVFJREFRQUJBb0lCQUZrbU9HSHY1aXlYbHZzVApaVlJkVUM1ODhYRmlNYitCQ2hyRTFzYmMzNVZXM1IrNW5JZ2RDNHEycTFKdUxwRzVIK2RRNkp0SDZ0bTlMVE1MCnJnWkxwbDY3QW1Ya3QyRGNGVERlM1BTNzRNazNWRE5nODk2MkZUUDhGY0F5dTFTT21McnV3Y0k1UmYzOW1DbFQKVzRJbGdjNWdXdFpFcW9yZU9iVVk0NmpqVXdVUWl4WHlUc2xock9PVDBreXlyYm5YcWU5Ym9TU3k5SS9LVVJscQp2WUtwTUFHWnFZN09NcXd2TlZpamlxZHl5QTdOb3B3dVh0aStmT244VTdwZEJaYzFrdmhZRDVjcXlEM1VhUGFLCktwa0JDeEVOY1NkZFc5SmlDdEd1U291Mk9icElIdUhjVU94clRZMXZKM0ZFNFRMRDJuMnRKcTBkOG5obElwN3IKU0dUVGZPMENnWUVBeTZnLzRGOWk5SjQ1YStscnJGMTBTSXE5V1ZTZjBldnc4MVVleFltVXNyYy9wd05OOTl6OQpiL05oSUpiaGFSRnZldE9GVVY0QmZUc21sRnJLYnl5NnRRazJQcHg4enZ6Zk5Md3hiSU1kdk9aejNIcTEycWZvCjRsOW15SUlaN1hlNlJGTGc4NGRQWnlwUWxXRTRBUEtNdjN0Q2k2cGVpSEt4NjBFRXBtdWJXRU1DZ1lFQTY0VDUKRlgvWnp0c3JFTkZpUTR5OHBhTEpZVHhsZnpMZm9iRWRFYUlhenErV2JSVmo4TVF1K2ltcGU2NGFQQk9OeVd5NAoraHNFenBBNlpkN0FoWWZKWXVZcU16YU0xd1dtcndrSlZaWFZScUY5dVlCSmFaRFBRblhGb3hVQjlzWGlFQ0NrCnlSSk9MempIM3FaSjlVVzNETkF4ZThZM21lLzFucDFjRXR6NWNHc0NnWUFTTzFhMGxIVjhacW5IVWxjMFVBMTMKN1F1MGNwSDRMZ0lkRnBLeHBuWnNaV0ZLWjA1VWtURVRFNXV2V2pLRndHelZkeGdwUjV3a2hPWVlRK1I1Zld5ZApobHlYMEZTUUJ5MUlRRXpBWlNDRlo3QVpuZGFuNDM1Q3ZiMnExNUxRb25aSFpaQUQzU29ybHlzdHBFMXFNRXlQClc4NkNTRmM4S2VCcHFpRnJjSml3bHdLQmdRREpxT0xxSUwycm5BZms3NVBXeVFPaVE1OXdyWmt1YjY0Q01iZjEKS0RzUjdGQzkrRW5KbHdHdVc4dnR4YVphK0ZjNE4rcXU1RUdhYU81SDJaSTVBNHBSTDBqRTd4bHE1MERRc01rWQpTaUlDeHpYeWhzRFZMaFA1RVFSMzNmMy9nWEpPWXRVV0FhR0dWM1R6MUtpUTVlK1ZmaEpRcStsaDJwQVNEeVVPClZiMFRId0tCZ0J0NTVMUjVKSnJieitiRnN6ZzhpTSt3WTUreVpzVzFXZC8xV0NzNDV1aTVoVTFzOUFQd0NKNlkKdmF4RklXcEZ5VXdFNldVZGo2OTJFTVhPaXFrTFBpWWhkN3dydGtjY2xsWTJCYkh5ODZvMTIzcDVmMjA1RDNQcApGM1llQVA4bmlJNHYySFZXQ2JJWTN1UlRMazhmTHYvVi83VHQ5V0FMZmlKT3B3YzVBQm16Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: extension-apiserver-authentication-reader
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basic-example-apiserver-auth-reader
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: basic-example-apiserver-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: basic-example-apiserver-auth-reader
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: basic-example-apiserver-auth-delegator
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basic-example-controller
  namespace: default
rules:
  - apiGroups:
      - 'innsmouth.k8s.io'
      - 'kingsport.k8s.io'
      - 'miskatonic.k8s.io'
      - 'olympus.k8s.io'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - 'configmaps'
      - 'namespaces'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - 'list'
      - 'watch'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: basic-example-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: basic-example-controller
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
