
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.innsmouth.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1
  group: innsmouth.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo0Q0NRQ1RNMjUxUm9kTE96QU5CZ2txaGtpRzl3MEJBUXNGQURCdE1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVN3d0tnWURWUVFERENOaVlYTnBZeTFsZUdGdGNHeGxMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwCmVUQWVGdzB5TURBNE1qVXhOVE01TURsYUZ3MHlNVEE0TWpVeE5UTTVNRGxhTUcweEN6QUpCZ05WQkFZVEFuVnUKTVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3QwpiM1V4TERBcUJnTlZCQU1NSTJKaGMybGpMV1Y0WVcxd2JHVXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM3JKRysrbzd4T3FhdUsvR0dkSE8KcnZkZ2RRTjAxUlJhNGtpb3htNmtkZVFYNHZDMmtMTGZCS285azJTVjI5RUxmK3A2QnBMS0Q0dE04OFJNTjQyVApCcVg4QzNBUVU2TW80bEo3UE9LclliTW1yTzhrajd6WUZZTXpEVkRVQjQ2Tmp2dUx6ZDV3amNXRnZsQ3NIOFRGCjR3ZUcrSEpzb25DM2NiOGx4dTd6MUVucmtNQ0lhNmNSTGVOSS9JUFBIaEprem82d2ozTXllSWJWL1B3WWJNcTIKaGs2bTZrdjJFTXYyNm8yZEhuNTVWL01QdktFR3A2SXNoNzJCNlBSWmZZNHpDcXNwN0ltaGZsZnBGL1BWOWFhNwpxdStCL2lzNFVnb1NpUnBWd0RtSzA3SFU2N0JXUk5pY250Rjl4UEJSS3pSLzJpM3Fqc2diaGhISVA2djM2ZTdkCmh3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDdGJSZTJiYWZaZnZ4NXpZaWRLVEdRSmZQWE9PT3cKNFlrRzM0Z0d5RFZDTXY4bXNucmlhNTRtZ3JMRUxmN0xZWTc0ckVyb0FEc3d1VU1iZUgyTEt2S1FIaVhVQUtqeAprZmJBbUNNY3BjUGNlc2wvTmduOVdsRzE4Ym91emMrTVZ5aGtVM29iNjZVUDVFenVPQ000ek8rUUU4a2RmVW1FClhlYXhUY2RIL2VaTnh1OFh3bWJEMmJHZXNjcVMyYVhhTGpPc3BaNE8wTi8yRTA3YTlDVm16azI4b2M3VThqamQKc0wzalF1eEZ4UGxkYnFSaFFFRnFYY0FyZkJIT28rZEtvRnQzVEJjV01NM0EvOUVxTXFpRFB3Z2srY0FiOXArTQpNMS9IdTVTSk9iMGNoNDBBWjlwUXJkZEc2akFVcHNuN0k2cGszcnNGTGVIdXpiZDVzbXRtalBoUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.kingsport.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1
  group: kingsport.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo0Q0NRQ1RNMjUxUm9kTE96QU5CZ2txaGtpRzl3MEJBUXNGQURCdE1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVN3d0tnWURWUVFERENOaVlYTnBZeTFsZUdGdGNHeGxMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwCmVUQWVGdzB5TURBNE1qVXhOVE01TURsYUZ3MHlNVEE0TWpVeE5UTTVNRGxhTUcweEN6QUpCZ05WQkFZVEFuVnUKTVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3QwpiM1V4TERBcUJnTlZCQU1NSTJKaGMybGpMV1Y0WVcxd2JHVXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM3JKRysrbzd4T3FhdUsvR0dkSE8KcnZkZ2RRTjAxUlJhNGtpb3htNmtkZVFYNHZDMmtMTGZCS285azJTVjI5RUxmK3A2QnBMS0Q0dE04OFJNTjQyVApCcVg4QzNBUVU2TW80bEo3UE9LclliTW1yTzhrajd6WUZZTXpEVkRVQjQ2Tmp2dUx6ZDV3amNXRnZsQ3NIOFRGCjR3ZUcrSEpzb25DM2NiOGx4dTd6MUVucmtNQ0lhNmNSTGVOSS9JUFBIaEprem82d2ozTXllSWJWL1B3WWJNcTIKaGs2bTZrdjJFTXYyNm8yZEhuNTVWL01QdktFR3A2SXNoNzJCNlBSWmZZNHpDcXNwN0ltaGZsZnBGL1BWOWFhNwpxdStCL2lzNFVnb1NpUnBWd0RtSzA3SFU2N0JXUk5pY250Rjl4UEJSS3pSLzJpM3Fqc2diaGhISVA2djM2ZTdkCmh3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDdGJSZTJiYWZaZnZ4NXpZaWRLVEdRSmZQWE9PT3cKNFlrRzM0Z0d5RFZDTXY4bXNucmlhNTRtZ3JMRUxmN0xZWTc0ckVyb0FEc3d1VU1iZUgyTEt2S1FIaVhVQUtqeAprZmJBbUNNY3BjUGNlc2wvTmduOVdsRzE4Ym91emMrTVZ5aGtVM29iNjZVUDVFenVPQ000ek8rUUU4a2RmVW1FClhlYXhUY2RIL2VaTnh1OFh3bWJEMmJHZXNjcVMyYVhhTGpPc3BaNE8wTi8yRTA3YTlDVm16azI4b2M3VThqamQKc0wzalF1eEZ4UGxkYnFSaFFFRnFYY0FyZkJIT28rZEtvRnQzVEJjV01NM0EvOUVxTXFpRFB3Z2srY0FiOXArTQpNMS9IdTVTSk9iMGNoNDBBWjlwUXJkZEc2akFVcHNuN0k2cGszcnNGTGVIdXpiZDVzbXRtalBoUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.miskatonic.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1beta1
  group: miskatonic.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo0Q0NRQ1RNMjUxUm9kTE96QU5CZ2txaGtpRzl3MEJBUXNGQURCdE1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVN3d0tnWURWUVFERENOaVlYTnBZeTFsZUdGdGNHeGxMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwCmVUQWVGdzB5TURBNE1qVXhOVE01TURsYUZ3MHlNVEE0TWpVeE5UTTVNRGxhTUcweEN6QUpCZ05WQkFZVEFuVnUKTVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3QwpiM1V4TERBcUJnTlZCQU1NSTJKaGMybGpMV1Y0WVcxd2JHVXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM3JKRysrbzd4T3FhdUsvR0dkSE8KcnZkZ2RRTjAxUlJhNGtpb3htNmtkZVFYNHZDMmtMTGZCS285azJTVjI5RUxmK3A2QnBMS0Q0dE04OFJNTjQyVApCcVg4QzNBUVU2TW80bEo3UE9LclliTW1yTzhrajd6WUZZTXpEVkRVQjQ2Tmp2dUx6ZDV3amNXRnZsQ3NIOFRGCjR3ZUcrSEpzb25DM2NiOGx4dTd6MUVucmtNQ0lhNmNSTGVOSS9JUFBIaEprem82d2ozTXllSWJWL1B3WWJNcTIKaGs2bTZrdjJFTXYyNm8yZEhuNTVWL01QdktFR3A2SXNoNzJCNlBSWmZZNHpDcXNwN0ltaGZsZnBGL1BWOWFhNwpxdStCL2lzNFVnb1NpUnBWd0RtSzA3SFU2N0JXUk5pY250Rjl4UEJSS3pSLzJpM3Fqc2diaGhISVA2djM2ZTdkCmh3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDdGJSZTJiYWZaZnZ4NXpZaWRLVEdRSmZQWE9PT3cKNFlrRzM0Z0d5RFZDTXY4bXNucmlhNTRtZ3JMRUxmN0xZWTc0ckVyb0FEc3d1VU1iZUgyTEt2S1FIaVhVQUtqeAprZmJBbUNNY3BjUGNlc2wvTmduOVdsRzE4Ym91emMrTVZ5aGtVM29iNjZVUDVFenVPQ000ek8rUUU4a2RmVW1FClhlYXhUY2RIL2VaTnh1OFh3bWJEMmJHZXNjcVMyYVhhTGpPc3BaNE8wTi8yRTA3YTlDVm16azI4b2M3VThqamQKc0wzalF1eEZ4UGxkYnFSaFFFRnFYY0FyZkJIT28rZEtvRnQzVEJjV01NM0EvOUVxTXFpRFB3Z2srY0FiOXArTQpNMS9IdTVTSk9iMGNoNDBBWjlwUXJkZEc2akFVcHNuN0k2cGszcnNGTGVIdXpiZDVzbXRtalBoUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.olympus.k8s.io
  labels:
    api: basic-example
    apiserver: "true"
spec:
  version: v1beta1
  group: olympus.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: basic-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo0Q0NRQ1RNMjUxUm9kTE96QU5CZ2txaGtpRzl3MEJBUXNGQURCdE1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVN3d0tnWURWUVFERENOaVlYTnBZeTFsZUdGdGNHeGxMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwCmVUQWVGdzB5TURBNE1qVXhOVE01TURsYUZ3MHlNVEE0TWpVeE5UTTVNRGxhTUcweEN6QUpCZ05WQkFZVEFuVnUKTVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3QwpiM1V4TERBcUJnTlZCQU1NSTJKaGMybGpMV1Y0WVcxd2JHVXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM3JKRysrbzd4T3FhdUsvR0dkSE8KcnZkZ2RRTjAxUlJhNGtpb3htNmtkZVFYNHZDMmtMTGZCS285azJTVjI5RUxmK3A2QnBMS0Q0dE04OFJNTjQyVApCcVg4QzNBUVU2TW80bEo3UE9LclliTW1yTzhrajd6WUZZTXpEVkRVQjQ2Tmp2dUx6ZDV3amNXRnZsQ3NIOFRGCjR3ZUcrSEpzb25DM2NiOGx4dTd6MUVucmtNQ0lhNmNSTGVOSS9JUFBIaEprem82d2ozTXllSWJWL1B3WWJNcTIKaGs2bTZrdjJFTXYyNm8yZEhuNTVWL01QdktFR3A2SXNoNzJCNlBSWmZZNHpDcXNwN0ltaGZsZnBGL1BWOWFhNwpxdStCL2lzNFVnb1NpUnBWd0RtSzA3SFU2N0JXUk5pY250Rjl4UEJSS3pSLzJpM3Fqc2diaGhISVA2djM2ZTdkCmh3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDdGJSZTJiYWZaZnZ4NXpZaWRLVEdRSmZQWE9PT3cKNFlrRzM0Z0d5RFZDTXY4bXNucmlhNTRtZ3JMRUxmN0xZWTc0ckVyb0FEc3d1VU1iZUgyTEt2S1FIaVhVQUtqeAprZmJBbUNNY3BjUGNlc2wvTmduOVdsRzE4Ym91emMrTVZ5aGtVM29iNjZVUDVFenVPQ000ek8rUUU4a2RmVW1FClhlYXhUY2RIL2VaTnh1OFh3bWJEMmJHZXNjcVMyYVhhTGpPc3BaNE8wTi8yRTA3YTlDVm16azI4b2M3VThqamQKc0wzalF1eEZ4UGxkYnFSaFFFRnFYY0FyZkJIT28rZEtvRnQzVEJjV01NM0EvOUVxTXFpRFB3Z2srY0FiOXArTQpNMS9IdTVTSk9iMGNoNDBBWjlwUXJkZEc2akFVcHNuN0k2cGszcnNGTGVIdXpiZDVzbXRtalBoUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
---
apiVersion: v1
kind: Service
metadata:
  name: basic-example
  namespace: default
  labels:
    api: basic-example
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: basic-example
    apiserver: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-example
  namespace: default
  labels:
    api: basic-example
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: basic-example
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: basic-example
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: example.io/basic
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        - "--disable-admission-plugins=MutatingAdmissionWebhook,ValidatingAdmissionWebhook,NamespaceLifecycle"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: controller
        image: example.io/basic
        imagePullPolicy: IfNotPresent
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: basic-example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: default
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: "etcd"
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
        env:
        - name: ETCD_DATA_DIR
          value: /etcd-data-dir
        command:
        - /usr/local/bin/etcd
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://localhost:2379
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data-dir
          mountPath: /etcd-data-dir
        readinessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
  volumeClaimTemplates:
  - metadata:
     name: etcd-data-dir
     annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
         storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: default
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: etcd
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: basic-example
  namespace: default
  labels:
    api: basic-example
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURURENDQWpRQ0NRQ01pajhFQ3hLNFR6QU5CZ2txaGtpRzl3MEJBUVVGQURCdE1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVN3d0tnWURWUVFERENOaVlYTnBZeTFsZUdGdGNHeGxMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwCmVUQWVGdzB5TURBNE1qVXhOVE01TURsYUZ3MHlNVEE0TWpVeE5UTTVNRGxhTUdNeEN6QUpCZ05WQkFZVEFuVnUKTVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3QwpiM1V4SWpBZ0JnTlZCQU1NR1dKaGMybGpMV1Y0WVcxd2JHVXVaR1ZtWVhWc2RDNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNvaGIzL1FJclBjZTBRU1lBSGZQMWJPQ21PYm1ZQStlYkQKWFhSRXd4cXRLUlRDdnZGRjdNNHJGclZMU0lMVW4vZlErQ1p1SEtialBKR1VVdStrTll5VXJ6azZmbzhOdHZpQgpNZXdtVHExZHluL2lOUnYrWVJpYXprd25mcHhmQkhoSEFaTk01dHJRSmJyalc0QUxmRVcwa2ZVdVlQdWx1MmZICmxkTUZOVHRYNDA0dWJHWjJzLzgrTEg0VDRIdDBIcVpKVG90Vk1PTHhUMFBjTUs4dVhhUlpkRTB1bFpOSm1nMEwKV0wzMDdZeG81Vi9DdllQVzFqZ1pwek9TVkdPVkhDU0hRVFJBVCsyQW9xVUNHSlpTY09EVDlLQUZFeC9IdmRvVwo4aXkvZGY3WmVxZWpHQjNGRnZ5bkdEQ3pmcjQ3MkhNVU5jMWdGZW55NW5wTTllTmxMc1lQQWdNQkFBRXdEUVlKCktvWklodmNOQVFFRkJRQURnZ0VCQUp5MHd4TFZLY0Z6azR3VmcvVHZZSnhRTXdVWFlFTEpJQXpqVi8vbFRsMEYKK2xySmpRUFg2WUhuaWxueDdJQ1ZXL29Mb0VqUTNWVUpaOWU5OUNqT1J3UmhVUHVqekR4VUIxWmxhaGtzZ3EwaQpjQi9DNXg2b0F0cnpjS3U3M2Z5MFZHL01wcjFteFZ0OEEwQk1TT0VERmoxb240NVVEYVlXVDBzVm9BdVlvZHE3CjVrZElJTmFXaUtNWnJNRzZ2K1RPN29sOTZOWnBpWWVYSlVySXJOYzlJMHVwM0lmTlorcTc3S3NhbWwyNVFJU00KODlkL0FWUFZZengzYmlkbnpsVWZ2OWpidVhkV0YzYm9JUThIUkdZZXNzZkVxUHR6RHJCZWl5dnNwWGJUMWt4bwpwNm9rZ0pHeUlFeGtMMGhza1B6QVN2QlJBdW43T1hMbGp2Uk9hYUZFOXJnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ29oYjMvUUlyUGNlMFEKU1lBSGZQMWJPQ21PYm1ZQStlYkRYWFJFd3hxdEtSVEN2dkZGN000ckZyVkxTSUxVbi9mUStDWnVIS2JqUEpHVQpVdStrTll5VXJ6azZmbzhOdHZpQk1ld21UcTFkeW4vaU5SditZUmlhemt3bmZweGZCSGhIQVpOTTV0clFKYnJqClc0QUxmRVcwa2ZVdVlQdWx1MmZIbGRNRk5UdFg0MDR1YkdaMnMvOCtMSDRUNEh0MEhxWkpUb3RWTU9MeFQwUGMKTUs4dVhhUlpkRTB1bFpOSm1nMExXTDMwN1l4bzVWL0N2WVBXMWpnWnB6T1NWR09WSENTSFFUUkFUKzJBb3FVQwpHSlpTY09EVDlLQUZFeC9IdmRvVzhpeS9kZjdaZXFlakdCM0ZGdnluR0RDemZyNDcySE1VTmMxZ0Zlbnk1bnBNCjllTmxMc1lQQWdNQkFBRUNnZ0VBWmU0L05aejhXTzAzenBvbWJtRVRmWkZDMFh2RkJ1SWd5aHBFc1RLeGQvdFoKSzFJQzdhQ0dNMW5RM25CRmNnWXdCcDJSNFJoRGVUNnhiMTJheFYvK1lCQjhOUDFIMmF2S001cldrM1VUTjUrOApLajZsWi8raXVqLzlvQVhjM3p2ODVEWDN1cFFIMWM1OGMvaHNRb1l3UXovbFpPQVVWZkk4bTJQcjkwSnpXbnlPCisrTUhRVGdBZU5NczZWMDdza2FCOFVxMm13bGc5K1VIak9EVUVvQ0RFWGhWRTFLMUR5YU5PcDZqZGQ1U2tpV08KYUdwYyt1aFdWamJnTXhNMFBCR0hrR0QxMFFCY1A5Y0xnYjhWRENtYVdHYW02N24weDRuRnFCbit3MzdlZyt3UApQRDYrbEIxMEhvRFBKY1VkRHZTaktVN1l1RVMxd09KSDZVUUhwK1EzZ1FLQmdRRFZKalRPTVo0V1NpTWJrcEY5ClAreSt0NTA0bS9iREY0WGt6Ylhsb0tsRG9GYWx0UVVmWTBKeGQwYVZtbTdYWjkxMXhpYTJJM2RrZHBrNllEdWUKQjhxTytsbU1ab2gzcndMUTlGdU04VTFzb1RkYXV5Q2ZQY2QwNFArVUpOckd6aFJRcnV0clJSSGNMZTgvanRJUApickUyU0xLY2Evb0NWT3JQdDd1MkNrQVMrUUtCZ1FES1pzMkJuUGozZHozK2prTTdlMUxKdFVLQW5kZyt2UGh4CkUwZ3pmelZ6NE1YSURVYWUrZk9ia2lKa2tOWENmRTJBejFOWWlzZHd0VFQ5b0ZQdXU5VGtveDRTRDYxd1YwL2gKaUhwTEU0dmc0MjFaYkQ5RjQ3YkRJQ1d6T2tRenZRSGg3ajhGSlVVd25tNGk5UjJBT1paTnMrTjdUaUJCNURJUQpmcm8vcThOYlJ3S0JnUUN0V05Rck9Ua2JZWkhwMDZxVkZVOEIwQ3lDSkgxc0xvNUxCVzNBWVlnbklwZzFUZUhyCm8vc2VjbVdxTjUyYmU3SWxIVkRRWWttd0g3QUFSTkZYZFhpc0RUaVVzYktjdTIxcjZMOG9BZnI0dEtoakZycXkKSnprMmVlSUJabk95cVZqbVFVdmV3cDZDMWF5MG9QOS9ZNE9sNVR1MWNTOHpoRUl2U25yVDBzUkhhUUtCZ0FnbApwelFHYTRjYWg2Wk5kNnRYUlhmVkVmNDNYRkw2TEUzdzVzRWI1N3pvV1UyNkt4T1BJQjBzL3JGcG14RWZDOGVaCmtOTkprc21Zb2E5cjJyVUxYb0J0aUhKVnF6ZVFiQ2k1NDZKT0FSMW1TaXFGVHU2elFkSU00emVacXRFaVZJY1IKbmZ2SkNrWHd1cUl4bDZSbnJRTW5zSXB3RktCU1hTbUkwRnByd1l0VkFvR0JBTHF6dHlYa0JtNlB2bUpkWFhKYwp3Q0RhNnl4SDlCWFZTeTdYTzdLQVVqdUlQSWFzYnNTb3JLQUE3dTdmOFBoQ2s2OVh4WlAyUUtlZ0lydVFYQWlUCllmSzF4ZzYzQ080WHVqR2FiT21OODNDeG1qajBvaTVrdXUvUytzendTNWIzYzdQRis3NmZHYWs0RlNrQnFON3kKdG1CVlVmK04zdERYaWZEWm9IV1Jaa3p0Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
