name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  example:
    runs-on: ubuntu-latest
    name: Testing Examples
    steps:
      - uses: actions/checkout@v2
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
          sudo dpkg -i bazel_0.29.1-linux-x86_64.deb
          bash scripts/install_etcd.sh
          bash test/install-kubebuilder.sh
          make install
      - name: Testing on examples
        run: |
          cd example/basic
          PATH=$GOPATH/bin:$PATH:/tmp/test-etcd make test
  new:
    runs-on: ubuntu-latest
    name: Testing New Projects
    steps:
      - uses: actions/checkout@v2
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
          sudo dpkg -i bazel_0.29.1-linux-x86_64.deb
          bash scripts/install_etcd.sh
          bash test/install-kubebuilder.sh
          make install
      - name: Testing on new project
        run: |
          cd test/
          PATH=$GOPATH/bin:$PATH:/tmp/test-etcd make test