name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  new:
    runs-on: ubuntu-latest
    name: Testing New Projects
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.13
      - uses: actions/checkout@v2.3.1
        with:
          path: go/src/sigs.k8s.io/apiserver-builder-alpha/
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/go/pkg/mod
            ${{ github.workspace }}/.cache/bazel
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Workspace Preparing
        env:
          GOPATH: ${{ github.workspace }}/go
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/
        run: bash scripts/workspace-install.sh
      - name: Install
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/
        env:
          GOPATH: ${{ github.workspace }}/go
        run: make install
      - name: Testing on new project
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/test
        env:
          GOPATH: ${{ github.workspace }}/go
          GOBIN: ${{ github.workspace }}/go/bin
        run: |
          export PATH=${PATH}:${GOBIN}
          make test
  basic-example-build:
    runs-on: ubuntu-latest
    name: Testing Basic Example
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.13
      - uses: actions/checkout@v2.3.1
        with:
          path: go/src/sigs.k8s.io/apiserver-builder-alpha/
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/go/pkg/mod
            ${{ github.workspace }}/.cache/bazel
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Workspace Preparing
        env:
          GOPATH: ${{ github.workspace }}/go
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/
        run: bash scripts/workspace-install.sh
      - name: Install
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/
        env:
          GOPATH: ${{ github.workspace }}/go
        run: make install
      - name: Testing on examples
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/example/basic
        env:
          GOPATH: ${{ github.workspace }}/go
          GOBIN: ${{ github.workspace }}/go/bin
        run: |
          export PATH=${PATH}:${GOBIN}
          make test
  basic-example-container:
    runs-on: ubuntu-latest
    name: Testing Basic Example Container Build
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.13
      - uses: actions/checkout@v2.3.1
        with:
          path: go/src/sigs.k8s.io/apiserver-builder-alpha/
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0
      - name: Workspace Preparing
        env:
          GOPATH: ${{ github.workspace }}/go
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/
        run: bash scripts/workspace-install.sh
      - name: Install
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/
        env:
          GOPATH: ${{ github.workspace }}/go
        run: make install
      - name: Building and running container images
        working-directory: ${{ github.workspace }}/go/src/sigs.k8s.io/apiserver-builder-alpha/example/basic
        env:
          GOPATH: ${{ github.workspace }}/go
          GOBIN: ${{ github.workspace }}/go/bin
        run: |
          export PATH=${PATH}:${GOBIN}
          export IMAGE="example.io/basic"
          apiserver-boot build container --image ${IMAGE}
          kind load docker-image ${IMAGE} --name chart-testing
          kubectl create -f config/apiserver.yaml

          sleep 60 # Hold for 1min

          kubectl api-resources
          kubectl create -f sample/festival.yaml

          sleep 5 # Hold for 1min
          kubectl get fs festival-example -o jsonpath="{.spec.invited}" | grep 1 # successfully processed by controller
